
import { Book, BookCategory, PhysicalStatus } from './types';

// Функция для генерации простого ID из названия и автора
const generateId = (title: string, author: string): string => {
  const cleanedTitle = title.toLowerCase().replace(/[^a-z0-9а-яё]/g, '');
  const cleanedAuthor = author.toLowerCase().replace(/[^a-z0-9а-яё]/g, '');
  return `db-${cleanedTitle.substring(0, 15)}-${cleanedAuthor.substring(0, 15)}`;
};


export const initialBooks: Book[] = [
  {
    id: generateId('Хрустальный лебедь', 'AnnieBerezovskay'),
    title: 'Хрустальный лебедь',
    author: 'AnnieBerezovskay',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Скандинавские мифы', 'А.Н. Николаева'),
    title: 'Скандинавские мифы',
    author: 'А.Н. Николаева',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Славянские мифы', 'А.Н. Николаева'),
    title: 'Славянские мифы',
    author: 'А.Н. Николаева',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Овертайм', 'Ава Хоуп'),
    title: 'Овертайм',
    author: 'Ава Хоуп',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Последний сеанс', 'Агата Кристи'),
    title: 'Последний сеанс',
    author: 'Агата Кристи',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Метод книжной героини', 'Алекс Хилл'),
    title: 'Метод книжной героини',
    author: 'Алекс Хилл',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Передружба. Недоотношения', 'Алекс Хилл'),
    title: 'Передружба. Недоотношения',
    author: 'Алекс Хилл',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('После тебя только пепел', 'Алекс Хилл'),
    title: 'После тебя только пепел',
    author: 'Алекс Хилл',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Уничтожить королевство', 'александра кристо'),
    title: 'Уничтожить королевство',
    author: 'александра кристо',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Шах и мат', 'Али Хейзелвуд'),
    title: 'Шах и мат',
    author: 'Али Хейзелвуд',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Кровавая наследница', 'амели вэнь чжао'),
    title: 'Кровавая наследница',
    author: 'амели вэнь чжао',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Грация королевы небес. Тайна Адель', 'Ана шерри'),
    title: 'Грация королевы небес. Тайна Адель',
    author: 'Ана шерри',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Грация королевы небес',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Грация королевы небес. Тайна Марко', 'Ана шерри'),
    title: 'Грация королевы небес. Тайна Марко',
    author: 'Ана шерри',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Грация королевы небес',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Ла Элиза', 'Ана шерри'),
    title: 'Ла Элиза',
    author: 'Ана шерри',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Одно небо на двоих', 'Ана шерри'),
    title: 'Одно небо на двоих',
    author: 'Ана шерри',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Хрупкое равновесие 1', 'Ана шерри'),
    title: 'Хрупкое равновесие 1',
    author: 'Ана шерри',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Хрупкое равновесие',
    category: BookCategory.READ,
  },
  {
    id: generateId('Хрупкое равновесие 2', 'Ана шерри'),
    title: 'Хрупкое равновесие 2',
    author: 'Ана шерри',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Хрупкое равновесие',
    category: BookCategory.READ,
  },
  {
    id: generateId('Хрупкое равновесие 3', 'Ана шерри'),
    title: 'Хрупкое равновесие 3',
    author: 'Ана шерри',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Хрупкое равновесие',
    category: BookCategory.READ,
  },
  {
    id: generateId('Я подарю тебе крылья. Книга 1', 'Ана шерри'),
    title: 'Я подарю тебе крылья. Книга 1',
    author: 'Ана шерри',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Я подарю тебе крылья',
    category: BookCategory.READ,
  },
  {
    id: generateId('Я подарю тебе крылья. Книга 2', 'Ана шерри'),
    title: 'Я подарю тебе крылья. Книга 2',
    author: 'Ана шерри',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Я подарю тебе крылья',
    category: BookCategory.READ,
  },
  {
    id: generateId('#любовьненависть', 'Анна джейн'),
    title: '#любовьненависть',
    author: 'Анна джейн',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('#ненавистьлюбовь', 'Анна джейн'),
    title: '#ненавистьлюбовь',
    author: 'Анна джейн',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Влюбленная ведьма', 'Анна джейн'),
    title: 'Влюбленная ведьма',
    author: 'Анна джейн',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Восхитительная ведьма', 'Анна джейн'),
    title: 'Восхитительная ведьма',
    author: 'Анна джейн',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Наследница черного дракона', 'Анна джейн'),
    title: 'Наследница черного дракона',
    author: 'Анна джейн',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('По осколкам твоего сердце', 'Анна джейн'),
    title: 'По осколкам твоего сердце',
    author: 'Анна джейн',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Поклонник', 'Анна джейн'),
    title: 'Поклонник',
    author: 'Анна джейн',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Тайна черного дракона', 'Анна джейн'),
    title: 'Тайна черного дракона',
    author: 'Анна джейн',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Твоё сердце будет разбито', 'Анна джейн'),
    title: 'Твоё сердце будет разбито',
    author: 'Анна джейн',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('До того как', 'анна тодд'),
    title: 'До того как',
    author: 'анна тодд',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'После',
    category: BookCategory.READ,
  },
  {
    id: generateId('Никак не меньше', 'анна тодд'),
    title: 'Никак не меньше',
    author: 'анна тодд',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'После',
    category: BookCategory.READ,
  },
  {
    id: generateId('Ничего больше', 'анна тодд'),
    title: 'Ничего больше',
    author: 'анна тодд',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'После',
    category: BookCategory.READ,
  },
  {
    id: generateId('После', 'анна тодд'),
    title: 'После',
    author: 'анна тодд',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'После',
    category: BookCategory.READ,
  },
  {
    id: generateId('После – долго и счастливо', 'анна тодд'),
    title: 'После – долго и счастливо',
    author: 'анна тодд',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'После',
    category: BookCategory.READ,
  },
  {
    id: generateId('После падения', 'анна тодд'),
    title: 'После падения',
    author: 'анна тодд',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'После',
    category: BookCategory.READ,
  },
  {
    id: generateId('После ссоры', 'анна тодд'),
    title: 'После ссоры',
    author: 'анна тодд',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'После',
    category: BookCategory.READ,
  },
  {
    id: generateId('Самая тёмная луна', 'анна тодд'),
    title: 'Самая тёмная луна',
    author: 'анна тодд',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Самые яркие звезды', 'анна тодд'),
    title: 'Самые яркие звезды',
    author: 'анна тодд',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Сестры Спринг', 'анна тодд'),
    title: 'Сестры Спринг',
    author: 'анна тодд',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Алая зима', 'аннетт мари'),
    title: 'Алая зима',
    author: 'аннетт мари',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Трилогия алой зимы',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Бессмертный огонь', 'аннетт мари'),
    title: 'Бессмертный огонь',
    author: 'аннетт мари',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Трилогия алой зимы',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Темная буря', 'аннетт мари'),
    title: 'Темная буря',
    author: 'аннетт мари',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Трилогия алой зимы',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Трилогия алой зимы', 'аннетт мари'),
    title: 'Трилогия алой зимы',
    author: 'аннетт мари',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Трилогия алой зимы',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Вечность в тебе', 'аннэ фрейтаг'),
    title: 'Вечность в тебе',
    author: 'аннэ фрейтаг',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Мне не жаль', 'аннэ фрейтаг'),
    title: 'Мне не жаль',
    author: 'аннэ фрейтаг',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Счастье рядом', 'аннэ фрейтаг'),
    title: 'Счастье рядом',
    author: 'аннэ фрейтаг',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Вишневый сад', 'Антон Чехов'),
    title: 'Вишневый сад',
    author: 'Антон Чехов',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Из моего окна', 'Ариана Годой'),
    title: 'Из моего окна',
    author: 'Ариана Годой',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Из моего окна',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Через мое окно', 'Ариана Годой'),
    title: 'Через мое окно',
    author: 'Ариана Годой',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Из моего окна',
    category: BookCategory.READ,
  },
  {
    id: generateId('Влюбить за 90 секунд', 'ася лавринович'),
    title: 'Влюбить за 90 секунд',
    author: 'ася лавринович',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Все из-за тебя', 'ася лавринович'),
    title: 'Все из-за тебя',
    author: 'ася лавринович',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Загадай любовь', 'ася лавринович'),
    title: 'Загадай любовь',
    author: 'ася лавринович',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Зимняя любовь', 'ася лавринович'),
    title: 'Зимняя любовь',
    author: 'ася лавринович',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Любовь не по сценарию', 'ася лавринович'),
    title: 'Любовь не по сценарию',
    author: 'ася лавринович',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Любовь под напряжением', 'ася лавринович'),
    title: 'Любовь под напряжением',
    author: 'ася лавринович',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Не дружи со мной', 'ася лавринович'),
    title: 'Не дружи со мной',
    author: 'ася лавринович',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Не спасай меня', 'ася лавринович'),
    title: 'Не спасай меня',
    author: 'ася лавринович',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Нелюбовь сероглазого короля', 'ася лавринович'),
    title: 'Нелюбовь сероглазого короля',
    author: 'ася лавринович',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('От одного Зайца', 'ася лавринович'),
    title: 'От одного Зайца',
    author: 'ася лавринович',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Поцелуй под омелой', 'ася лавринович'),
    title: 'Поцелуй под омелой',
    author: 'ася лавринович',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Самая белая ночь', 'ася лавринович'),
    title: 'Самая белая ночь',
    author: 'ася лавринович',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Сказка о снежной принцессе', 'ася лавринович'),
    title: 'Сказка о снежной принцессе',
    author: 'ася лавринович',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Там, где живет любовь', 'ася лавринович'),
    title: 'Там, где живет любовь',
    author: 'ася лавринович',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Только попробуй уйти', 'ася лавринович'),
    title: 'Только попробуй уйти',
    author: 'ася лавринович',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Ты мое счастье', 'ася лавринович'),
    title: 'Ты мое счастье',
    author: 'ася лавринович',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Худшие подруги', 'ася лавринович'),
    title: 'Худшие подруги',
    author: 'ася лавринович',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Грозовой перевал', 'Бронте Эмили'),
    title: 'Грозовой перевал',
    author: 'Бронте Эмили',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Быстро падая', 'бьянка иосивони'),
    title: 'Быстро падая',
    author: 'бьянка иосивони',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Взлетая высоко', 'бьянка иосивони'),
    title: 'Взлетая высоко',
    author: 'бьянка иосивони',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Спор на сердце', 'Вероника Фокс'),
    title: 'Спор на сердце',
    author: 'Вероника Фокс',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Достойный жених. Книга 1', 'Викрам Сет'),
    title: 'Достойный жених. Книга 1',
    author: 'Викрам Сет',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Достойный жених',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Своя комната', 'Вирджиния Вулф'),
    title: 'Своя комната',
    author: 'Вирджиния Вулф',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Взломать смерть', 'Герман Рыльский, Тамара Рыльская'),
    title: 'Взломать смерть',
    author: 'Герман Рыльский, Тамара Рыльская',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Артур, Луи и Адель', 'Дана Делон'),
    title: 'Артур, Луи и Адель',
    author: 'Дана Делон',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Будь моим', 'Дана Делон'),
    title: 'Будь моим',
    author: 'Дана Делон',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('В ореоле тьмы', 'Дана Делон'),
    title: 'В ореоле тьмы',
    author: 'Дана Делон',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Непрожитая жизнь', 'Дана Делон'),
    title: 'Непрожитая жизнь',
    author: 'Дана Делон',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Падающая звезда', 'Дана Делон'),
    title: 'Падающая звезда',
    author: 'Дана Делон',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Под небом парижа', 'Дана Делон'),
    title: 'Под небом парижа',
    author: 'Дана Делон',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Шестое чувство', 'Дана Делон'),
    title: 'Шестое чувство',
    author: 'Дана Делон',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Безумная одержимость', 'Даниэль Лори'),
    title: 'Безумная одержимость',
    author: 'Даниэль Лори',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Сумасшедшая одержимость', 'Даниэль Лори'),
    title: 'Сумасшедшая одержимость',
    author: 'Даниэль Лори',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Темное искушение', 'Даниэль Лори'),
    title: 'Темное искушение',
    author: 'Даниэль Лори',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Неночь', 'Джей Кристофф'),
    title: 'Неночь',
    author: 'Джей Кристофф',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('весь этот свет', 'джейми магвайр'),
    title: 'весь этот свет',
    author: 'джейми магвайр',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Мое прекрасное забвение. Моя прекрасная свадьба (сборник)', 'джейми магвайр'),
    title: 'Мое прекрасное забвение. Моя прекрасная свадьба (сборник)',
    author: 'джейми магвайр',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('мое прекрасное несчастье', 'джейми магвайр'),
    title: 'мое прекрасное несчастье',
    author: 'джейми магвайр',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Мое ходячее несчастье', 'джейми магвайр'),
    title: 'Мое ходячее несчастье',
    author: 'джейми магвайр',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Почти прекрасны', 'джейми магвайр'),
    title: 'Почти прекрасны',
    author: 'джейми магвайр',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Война двух королев', 'Дженифер Арметроут'),
    title: 'Война двух королев',
    author: 'Дженифер Арметроут',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Из крови и пепла',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Душа из пепла и крови', 'Дженифер Арметроут'),
    title: 'Душа из пепла и крови',
    author: 'Дженифер Арметроут',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Из крови и пепла',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Из крови и пепла', 'Дженифер Арметроут'),
    title: 'Из крови и пепла',
    author: 'Дженифер Арметроут',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Из крови и пепла',
    category: BookCategory.READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Искушение', 'Дженифер Арметроут'),
    title: 'Искушение',
    author: 'Дженифер Арметроут',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Королевство плоти и огня', 'Дженифер Арметроут'),
    title: 'Королевство плоти и огня',
    author: 'Дженифер Арметроут',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Из крови и пепла',
    category: BookCategory.READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Корона из золотых костей', 'Дженифер Арметроут'),
    title: 'Корона из золотых костей',
    author: 'Дженифер Арметроут',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Из крови и пепла',
    category: BookCategory.READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Лунный свет', 'Дженифер Арметроут'),
    title: 'Лунный свет',
    author: 'Дженифер Арметроут',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Обсидиан', 'Дженифер Арметроут'),
    title: 'Обсидиан',
    author: 'Дженифер Арметроут',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Огонек в пламени', 'Дженифер Арметроут'),
    title: 'Огонек в пламени',
    author: 'Дженифер Арметроут',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Тень и искры', 'Дженифер Арметроут'),
    title: 'Тень и искры',
    author: 'Дженифер Арметроут',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Игры наследников', 'Дженнифер Линн Барнс'),
    title: 'Игры наследников',
    author: 'Дженнифер Линн Барнс',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Игры наследников',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Наследие Хоторнов', 'Дженнифер Линн Барнс'),
    title: 'Наследие Хоторнов',
    author: 'Дженнифер Линн Барнс',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Игры наследников',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Последний гамбит', 'Дженнифер Линн Барнс'),
    title: 'Последний гамбит',
    author: 'Дженнифер Линн Барнс',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Игры наследников',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Гарри Поттер и Дары смерти', 'Джоан Роулинг'),
    title: 'Гарри Поттер и Дары смерти',
    author: 'Джоан Роулинг',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Гарри Поттер',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Гарри Поттер и Кубок Огня', 'Джоан Роулинг'),
    title: 'Гарри Поттер и Кубок Огня',
    author: 'Джоан Роулинг',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Гарри Поттер',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Гарри Поттер и Орден Феникса', 'Джоан Роулинг'),
    title: 'Гарри Поттер и Орден Феникса',
    author: 'Джоан Роулинг',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Гарри Поттер',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Гарри Поттер и Принц-полукровка', 'Джоан Роулинг'),
    title: 'Гарри Поттер и Принц-полукровка',
    author: 'Джоан Роулинг',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Гарри Поттер',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Гарри Поттер и Проклятое дитя', 'Джоан Роулинг'),
    title: 'Гарри Поттер и Проклятое дитя',
    author: 'Джоан Роулинг',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Гарри Поттер',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Гарри Поттер и Тайная комната', 'Джоан Роулинг'),
    title: 'Гарри Поттер и Тайная комната',
    author: 'Джоан Роулинг',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Гарри Поттер',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Гарри Поттер и узник Азкабана', 'Джоан Роулинг'),
    title: 'Гарри Поттер и узник Азкабана',
    author: 'Джоан Роулинг',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Гарри Поттер',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Гарри Поттер и философский камень', 'Джоан Роулинг'),
    title: 'Гарри Поттер и философский камень',
    author: 'Джоан Роулинг',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Гарри Поттер',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('До встречи с тобой', 'Джоджо мойес'),
    title: 'До встречи с тобой',
    author: 'Джоджо мойес',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Однажды в феврале', 'Джули Джордисон'),
    title: 'Однажды в феврале',
    author: 'Джули Джордисон',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Лисья тень', 'Джули Кагава'),
    title: 'Лисья тень',
    author: 'Джули Кагава',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Серия железные фейри', 'Джули Кагава'),
    title: 'Серия железные фейри',
    author: 'Джули Кагава',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Железные фейри',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Девственница на три дня', 'Дэй Лакки'),
    title: 'Девственница на три дня',
    author: 'Дэй Лакки',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Отцы и дети', 'Иван Тургенев'),
    title: 'Отцы и дети',
    author: 'Иван Тургенев',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Камень, ножницы, бумага', 'Инес Гарланд'),
    title: 'Камень, ножницы, бумага',
    author: 'Инес Гарланд',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Виноват кофе', 'К.О. В.Ш'),
    title: 'Виноват кофе',
    author: 'К.О. В.Ш',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Не отпускай меня', 'Кадзуо Исигуро'),
    title: 'Не отпускай меня',
    author: 'Кадзуо Исигуро',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Расстояние между нами', 'Кейси уэст'),
    title: 'Расстояние между нами',
    author: 'Кейси уэст',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Долго и счастливо', 'Кели орам'),
    title: 'Долго и счастливо',
    author: 'Кели орам',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Синдер и элла', 'Кели орам'),
    title: 'Синдер и элла',
    author: 'Кели орам',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('До упора', 'Кендалл Райан'),
    title: 'До упора',
    author: 'Кендалл Райан',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Игра в обороне', 'Кендалл Райан'),
    title: 'Игра в обороне',
    author: 'Кендалл Райан',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Сравнять счет', 'Кендалл Райан'),
    title: 'Сравнять счет',
    author: 'Кендалл Райан',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Охота на Джека-потрошителя', 'Керри манискалко'),
    title: 'Охота на Джека-потрошителя',
    author: 'Керри манискалко',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Охота на Джека-потрошителя',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Охота на дьявола', 'Керри манискалко'),
    title: 'Охота на дьявола',
    author: 'Керри манискалко',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Охота на Джека-потрошителя',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Охота на князя Дракулу', 'Керри манискалко'),
    title: 'Охота на князя Дракулу',
    author: 'Керри манискалко',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Охота на Джека-потрошителя',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Побег от Гудини', 'Керри манискалко'),
    title: 'Побег от Гудини',
    author: 'Керри манискалко',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Охота на Джека-потрошителя',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Царство Греха', 'Керри манискалко'),
    title: 'Царство Греха',
    author: 'Керри манискалко',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Царство',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Царство Проклятых', 'Керри манискалко'),
    title: 'Царство Проклятых',
    author: 'Керри манискалко',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Царство',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Царство Страха', 'Керри манискалко'),
    title: 'Царство Страха',
    author: 'Керри манискалко',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Царство',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Единственная', 'Кира касс'),
    title: 'Единственная',
    author: 'Кира касс',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Отбор',
    category: BookCategory.READ,
  },
  {
    id: generateId('Королева и фаворитка', 'Кира касс'),
    title: 'Королева и фаворитка',
    author: 'Кира касс',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Отбор',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Корона', 'Кира касс'),
    title: 'Корона',
    author: 'Кира касс',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Отбор',
    category: BookCategory.READ,
  },
  {
    id: generateId('Наследница', 'Кира касс'),
    title: 'Наследница',
    author: 'Кира касс',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Отбор',
    category: BookCategory.READ,
  },
  {
    id: generateId('Отбор', 'Кира касс'),
    title: 'Отбор',
    author: 'Кира касс',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Отбор',
    category: BookCategory.READ,
  },
  {
    id: generateId('Принц и гвардеец', 'Кира касс'),
    title: 'Принц и гвардеец',
    author: 'Кира касс',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Отбор',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Элита', 'Кира касс'),
    title: 'Элита',
    author: 'Кира касс',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Отбор',
    category: BookCategory.READ,
  },
  {
    id: generateId('Найди меня среди шторма', 'Кира мон'),
    title: 'Найди меня среди шторма',
    author: 'Кира мон',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Покажи мне звёзды', 'Кира мон'),
    title: 'Покажи мне звёзды',
    author: 'Кира мон',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Спаси меня от холода ночи', 'Кира мон'),
    title: 'Спаси меня от холода ночи',
    author: 'Кира мон',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Пятая зима', 'Китти Джонсон'),
    title: 'Пятая зима',
    author: 'Китти Джонсон',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Каждый день декабря', 'Китти Уилсон'),
    title: 'Каждый день декабря',
    author: 'Китти Уилсон',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Идеальная зависимость', 'Клаудиа Тан'),
    title: 'Идеальная зависимость',
    author: 'Клаудиа Тан',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Идеальная',
    category: BookCategory.READ,
  },
  {
    id: generateId('Идеальная иллюзия', 'Клаудиа Тан'),
    title: 'Идеальная иллюзия',
    author: 'Клаудиа Тан',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Идеальная',
    category: BookCategory.READ,
  },
  {
    id: generateId('Грязная сделка', 'Кора Рейли'),
    title: 'Грязная сделка',
    author: 'Кора Рейли',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Загубленная добродетель', 'Кора Рейли'),
    title: 'Загубленная добродетель',
    author: 'Кора Рейли',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Извращенная гордость', 'Кора Рейли'),
    title: 'Извращенная гордость',
    author: 'Кора Рейли',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Извращенная преданность', 'Кора Рейли'),
    title: 'Извращенная преданность',
    author: 'Кора Рейли',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Извращенное притяжения', 'Кора Рейли'),
    title: 'Извращенное притяжения',
    author: 'Кора Рейли',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Извращенные сердца', 'Кора Рейли'),
    title: 'Извращенные сердца',
    author: 'Кора Рейли',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Извращенные узы', 'Кора Рейли'),
    title: 'Извращенные узы',
    author: 'Кора Рейли',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Извращенные эмоции', 'Кора Рейли'),
    title: 'Извращенные эмоции',
    author: 'Кора Рейли',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Лука Витиелло', 'Кора Рейли'),
    title: 'Лука Витиелло',
    author: 'Кора Рейли',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Любовь взаперти', 'Кора Рейли'),
    title: 'Любовь взаперти',
    author: 'Кора Рейли',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Покоренная судьбой', 'Кора Рейли'),
    title: 'Покоренная судьбой',
    author: 'Кора Рейли',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Порождённая грехом', 'Кора Рейли'),
    title: 'Порождённая грехом',
    author: 'Кора Рейли',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Порождённая грехом',
    category: BookCategory.READ,
  },
  {
    id: generateId('Порождённая грехом. Последний ход принцессы', 'Кора Рейли'),
    title: 'Порождённая грехом. Последний ход принцессы',
    author: 'Кора Рейли',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Порождённая грехом',
    category: BookCategory.READ,
  },
  {
    id: generateId('Связанные долгом', 'Кора Рейли'),
    title: 'Связанные долгом',
    author: 'Кора Рейли',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Хроники мафии',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Связанные искушением', 'Кора Рейли'),
    title: 'Связанные искушением',
    author: 'Кора Рейли',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Хроники мафии',
    category: BookCategory.READ,
  },
  {
    id: generateId('Связанные кровью', 'Кора Рейли'),
    title: 'Связанные кровью',
    author: 'Кора Рейли',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Хроники мафии',
    category: BookCategory.READ,
  },
  {
    id: generateId('Связанные любовью', 'Кора Рейли'),
    title: 'Связанные любовью',
    author: 'Кора Рейли',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Хроники мафии',
    category: BookCategory.READ,
  },
  {
    id: generateId('Связанные местью', 'Кора Рейли'),
    title: 'Связанные местью',
    author: 'Кора Рейли',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Хроники мафии',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Связанные ненавистью', 'Кора Рейли'),
    title: 'Связанные ненавистью',
    author: 'Кора Рейли',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Хроники мафии',
    category: BookCategory.READ,
  },
  {
    id: generateId('Связанные прошлым', 'Кора Рейли'),
    title: 'Связанные прошлым',
    author: 'Кора Рейли',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Хроники мафии',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Связанные честью', 'Кора Рейли'),
    title: 'Связанные честью',
    author: 'Кора Рейли',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Хроники мафии',
    category: BookCategory.READ,
  },
  {
    id: generateId('Сладкое искушение', 'Кора Рейли'),
    title: 'Сладкое искушение',
    author: 'Кора Рейли',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Хрупкое желание', 'Кора Рейли'),
    title: 'Хрупкое желание',
    author: 'Кора Рейли',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Друзья с привилегиями', 'Кристина Мульер'),
    title: 'Друзья с привилегиями',
    author: 'Кристина Мульер',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Аспид', 'Кристина старк'),
    title: 'Аспид',
    author: 'Кристина старк',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Гончие Лилит', 'Кристина старк'),
    title: 'Гончие Лилит',
    author: 'Кристина старк',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Крылья', 'Кристина старк'),
    title: 'Крылья',
    author: 'Кристина старк',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Стигмалион', 'Кристина старк'),
    title: 'Стигмалион',
    author: 'Кристина старк',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Цианид', 'Кристина старк'),
    title: 'Цианид',
    author: 'Кристина старк',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Любовь в каждой строчке', 'кэт кроули'),
    title: 'Любовь в каждой строчке',
    author: 'кэт кроули',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Скажи что будешь помнить', 'кэти макгэрри'),
    title: 'Скажи что будешь помнить',
    author: 'кэти макгэрри',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Бездушный', 'Л. Дж. Шэн'),
    title: 'Бездушный',
    author: 'Л. Дж. Шэн',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Бессердечные изгои. Безжалостный соперник', 'Л. Дж. Шэн'),
    title: 'Бессердечные изгои. Безжалостный соперник',
    author: 'Л. Дж. Шэн',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Дьявол носит черный', 'Л. Дж. Шэн'),
    title: 'Дьявол носит черный',
    author: 'Л. Дж. Шэн',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Жестокий бог', 'Л. Дж. Шэн'),
    title: 'Жестокий бог',
    author: 'Л. Дж. Шэн',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Похититель поцелуев', 'Л. Дж. Шэн'),
    title: 'Похититель поцелуев',
    author: 'Л. Дж. Шэн',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Война и мир', 'Лев Толстой'),
    title: 'Война и мир',
    author: 'Лев Толстой',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Детство. Отрочество. Юность', 'Лев Толстой'),
    title: 'Детство. Отрочество. Юность',
    author: 'Лев Толстой',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Обоятельное чудовище', 'Лена сокол'),
    title: 'Обоятельное чудовище',
    author: 'Лена сокол',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Разрешите влюбиться', 'Лена сокол'),
    title: 'Разрешите влюбиться',
    author: 'Лена сокол',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Крах и восход', 'Ли бардуго'),
    title: 'Крах и восход',
    author: 'Ли бардуго',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Гришаверс',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Продажное королевство', 'Ли бардуго'),
    title: 'Продажное королевство',
    author: 'Ли бардуго',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Гришаверс',
    category: BookCategory.WANT_TO_READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Тень и кость', 'Ли бардуго'),
    title: 'Тень и кость',
    author: 'Ли бардуго',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Гришаверс',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Шестерка воронов', 'Ли бардуго'),
    title: 'Шестерка воронов',
    author: 'Ли бардуго',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Гришаверс',
    category: BookCategory.WANT_TO_READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Штурм и буря', 'Ли бардуго'),
    title: 'Штурм и буря',
    author: 'Ли бардуго',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Гришаверс',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Небеса все знают', 'Лина Мур'),
    title: 'Небеса все знают',
    author: 'Лина Мур',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Безупречная Луна', 'Лия Арден'),
    title: 'Безупречная Луна',
    author: 'Лия Арден',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Достойный высший суд', 'Лия Арден'),
    title: 'Достойный высший суд',
    author: 'Лия Арден',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Золото в тёмной ночи', 'Лия Арден'),
    title: 'Золото в тёмной ночи',
    author: 'Лия Арден',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Илос. Начало', 'Лия Арден'),
    title: 'Илос. Начало',
    author: 'Лия Арден',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Мара и морок', 'Лия Арден'),
    title: 'Мара и морок',
    author: 'Лия Арден',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Мара и морок',
    category: BookCategory.READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Мара и морок особенная тень', 'Лия Арден'),
    title: 'Мара и морок особенная тень',
    author: 'Лия Арден',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Мара и морок',
    category: BookCategory.READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Мара и Морок. 500 лет назад', 'Лия Арден'),
    title: 'Мара и Морок. 500 лет назад',
    author: 'Лия Арден',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Мара и морок',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Невеста Ноября', 'Лия Арден'),
    title: 'Невеста Ноября',
    author: 'Лия Арден',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Брось мне вызов', 'Лорен Лэндиш'),
    title: 'Брось мне вызов',
    author: 'Лорен Лэндиш',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Невеста на один день', 'Лорен Лэндиш'),
    title: 'Невеста на один день',
    author: 'Лорен Лэндиш',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Под маской, или Сила женщины', 'Луиза Мэй Олкотт'),
    title: 'Под маской, или Сила женщины',
    author: 'Луиза Мэй Олкотт',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Я загадаю тебя на лето', 'Максим Салос'),
    title: 'Я загадаю тебя на лето',
    author: 'Максим Салос',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Возвращение ангелов', 'Мара вульф'),
    title: 'Возвращение ангелов',
    author: 'Мара вульф',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Ангельская сага',
    category: BookCategory.READ,
  },
  {
    id: generateId('Гнев ангелов', 'Мара вульф'),
    title: 'Гнев ангелов',
    author: 'Мара вульф',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Ангельская сага',
    category: BookCategory.READ,
  },
  {
    id: generateId('Книга ангелов', 'Мара вульф'),
    title: 'Книга ангелов',
    author: 'Мара вульф',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Ангельская сага',
    category: BookCategory.READ,
  },
  {
    id: generateId('Сестра звёзд', 'Мара вульф'),
    title: 'Сестра звёзд',
    author: 'Мара вульф',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Сестра луны', 'Мара вульф'),
    title: 'Сестра луны',
    author: 'Мара вульф',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Сестра ночи', 'Мара вульф'),
    title: 'Сестра ночи',
    author: 'Мара вульф',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Унесенные ветром. Том 1', 'Маргарет Митчелл'),
    title: 'Унесенные ветром. Том 1',
    author: 'Маргарет Митчелл',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Унесенные ветром',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Будь моим Брейшо', 'Меган Брэнди'),
    title: 'Будь моим Брейшо',
    author: 'Меган Брэнди',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Короли старшей школы',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Короли старшей школы', 'Меган Брэнди'),
    title: 'Короли старшей школы',
    author: 'Меган Брэнди',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Короли старшей школы',
    category: BookCategory.READ,
  },
  {
    id: generateId('Неприятности в старшей школе', 'Меган Брэнди'),
    title: 'Неприятности в старшей школе',
    author: 'Меган Брэнди',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Короли старшей школы',
    category: BookCategory.READ,
  },
  {
    id: generateId('Парни из старшей школы', 'Меган Брэнди'),
    title: 'Парни из старшей школы',
    author: 'Меган Брэнди',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Короли старшей школы',
    category: BookCategory.READ,
  },
  {
    id: generateId('Сломай меня, если получится', 'Меган Брэнди'),
    title: 'Сломай меня, если получится',
    author: 'Меган Брэнди',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Короли старшей школы',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('моя вина', 'мерседес рон'),
    title: 'моя вина',
    author: 'мерседес рон',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Вина',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('наша вина', 'мерседес рон'),
    title: 'наша вина',
    author: 'мерседес рон',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Вина',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('твоя вина', 'мерседес рон'),
    title: 'твоя вина',
    author: 'мерседес рон',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Вина',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Загадай желание', 'Мия Лавьер'),
    title: 'Загадай желание',
    author: 'Мия Лавьер',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Доверься мне', 'мона кастен'),
    title: 'Доверься мне',
    author: 'мона кастен',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Again',
    category: BookCategory.WANT_TO_READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Начни сначала', 'мона кастен'),
    title: 'Начни сначала',
    author: 'мона кастен',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Again',
    category: BookCategory.READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Снова мечтай', 'мона кастен'),
    title: 'Снова мечтай',
    author: 'мона кастен',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Again',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Снова надейся', 'мона кастен'),
    title: 'Снова надейся',
    author: 'мона кастен',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Again',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Снова почувствуй', 'мона кастен'),
    title: 'Снова почувствуй',
    author: 'мона кастен',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Again',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Спаси меня', 'мона кастен'),
    title: 'Спаси меня',
    author: 'мона кастен',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Maxton Hall',
    category: BookCategory.READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Спаси нас', 'мона кастен'),
    title: 'Спаси нас',
    author: 'мона кастен',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Maxton Hall',
    category: BookCategory.READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Спаси себя', 'мона кастен'),
    title: 'Спаси себя',
    author: 'мона кастен',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Maxton Hall',
    category: BookCategory.READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Давай любить друг друга', 'Морган Монкомбл'),
    title: 'Давай любить друг друга',
    author: 'Морган Монкомбл',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Люби меня, я бегу от тебя', 'Морган Монкомбл'),
    title: 'Люби меня, я бегу от тебя',
    author: 'Морган Монкомбл',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Благословение небожителей 1', 'Мосян Тунсю'),
    title: 'Благословение небожителей 1',
    author: 'Мосян Тунсю',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Благословение небожителей',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Благословение небожителей 2', 'Мосян Тунсю'),
    title: 'Благословение небожителей 2',
    author: 'Мосян Тунсю',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Благословение небожителей',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Благословение небожителей 3', 'Мосян Тунсю'),
    title: 'Благословение небожителей 3',
    author: 'Мосян Тунсю',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Благословение небожителей',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Благословение небожителей 4', 'Мосян Тунсю'),
    title: 'Благословение небожителей 4',
    author: 'Мосян Тунсю',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Благословение небожителей',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Благословение небожителей 5', 'Мосян Тунсю'),
    title: 'Благословение небожителей 5',
    author: 'Мосян Тунсю',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Благословение небожителей',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Благословение небожителей 6', 'Мосян Тунсю'),
    title: 'Благословение небожителей 6',
    author: 'Мосян Тунсю',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Благословение небожителей',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Фурия. Художественный роман', 'Надежда Коновалова'),
    title: 'Фурия. Художественный роман',
    author: 'Надежда Коновалова',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Мертвые души', 'Николай Гоголь'),
    title: 'Мертвые души',
    author: 'Николай Гоголь',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Семь жизней', 'Нонна Монро'),
    title: 'Семь жизней',
    author: 'Нонна Монро',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Лисья нора', 'Нора Сакавич'),
    title: 'Лисья нора',
    author: 'Нора Сакавич',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Попутчица', 'Ольга Савельева'),
    title: 'Попутчица',
    author: 'Ольга Савельева',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Гордость и предубеждение', 'Остин Джейн'),
    title: 'Гордость и предубеждение',
    author: 'Остин Джейн',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('180 секунд', 'Парк Джессика'),
    title: '180 секунд',
    author: 'Парк Джессика',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Ближе к тебе', 'Парк Джессика'),
    title: 'Ближе к тебе',
    author: 'Парк Джессика',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Дыши со мной', 'Парк Джессика'),
    title: 'Дыши со мной',
    author: 'Парк Джессика',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Любовь между строк', 'Парк Джессика'),
    title: 'Любовь между строк',
    author: 'Парк Джессика',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Мэтт между строк', 'Парк Джессика'),
    title: 'Мэтт между строк',
    author: 'Парк Джессика',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Селеста между строк', 'Парк Джессика'),
    title: 'Селеста между строк',
    author: 'Парк Джессика',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Дорогой сводный братец', 'Пенелопа Уорд'),
    title: 'Дорогой сводный братец',
    author: 'Пенелопа Уорд',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Агрессор', 'Пенелопы Дуглас'),
    title: 'Агрессор',
    author: 'Пенелопы Дуглас',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('До тебя', 'Пенелопы Дуглас'),
    title: 'До тебя',
    author: 'Пенелопы Дуглас',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Доверие', 'Пенелопы Дуглас'),
    title: 'Доверие',
    author: 'Пенелопы Дуглас',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Дурное поведение', 'Пенелопы Дуглас'),
    title: 'Дурное поведение',
    author: 'Пенелопы Дуглас',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Именинница', 'Пенелопы Дуглас'),
    title: 'Именинница',
    author: 'Пенелопы Дуглас',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Испорченный', 'Пенелопы Дуглас'),
    title: 'Испорченный',
    author: 'Пенелопы Дуглас',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Конклав', 'Пенелопы Дуглас'),
    title: 'Конклав',
    author: 'Пенелопы Дуглас',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Курок', 'Пенелопы Дуглас'),
    title: 'Курок',
    author: 'Пенелопы Дуглас',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Ночь огня', 'Пенелопы Дуглас'),
    title: 'Ночь огня',
    author: 'Пенелопы Дуглас',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Падение', 'Пенелопы Дуглас'),
    title: 'Падение',
    author: 'Пенелопы Дуглас',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Панк 57', 'Пенелопы Дуглас'),
    title: 'Панк 57',
    author: 'Пенелопы Дуглас',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Пламя', 'Пенелопы Дуглас'),
    title: 'Пламя',
    author: 'Пенелопы Дуглас',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Соперник', 'Пенелопы Дуглас'),
    title: 'Соперник',
    author: 'Пенелопы Дуглас',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Сумрак', 'Пенелопы Дуглас'),
    title: 'Сумрак',
    author: 'Пенелопы Дуглас',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Убежище', 'Пенелопы Дуглас'),
    title: 'Убежище',
    author: 'Пенелопы Дуглас',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Метод подчинения', 'Полина Ветер'),
    title: 'Метод подчинения',
    author: 'Полина Ветер',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Безжалостная империя', 'Рина кент'),
    title: 'Безжалостная империя',
    author: 'Рина кент',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Империя желания', 'Рина кент'),
    title: 'Империя желания',
    author: 'Рина кент',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Ровно год', 'Робин Бенуэй'),
    title: 'Ровно год',
    author: 'Робин Бенуэй',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Хочу познакомиться', 'Рэйчел Уинтерс'),
    title: 'Хочу познакомиться',
    author: 'Рэйчел Уинтерс',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Мой любимый враг', 'Салли Торн'),
    title: 'Мой любимый враг',
    author: 'Салли Торн',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Как свести родителей за 30 дней', 'Сандра Кук'),
    title: 'Как свести родителей за 30 дней',
    author: 'Сандра Кук',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Фанатки тоже пьют кофе на завтрак', 'саша керн'),
    title: 'Фанатки тоже пьют кофе на завтрак',
    author: 'саша керн',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('До встречи в книжном', 'Саша Степанова, Оксана Багрий, Шабнова Екатерина, ALES, Рид Анви, Василий Ракша, Евгения Штольц, Владимир Торин'),
    title: 'До встречи в книжном',
    author: 'Саша Степанова, Оксана Багрий, Шабнова Екатерина, ALES, Рид Анви, Василий Ракша, Евгения Штольц, Владимир Торин',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Солярис', 'Станислав Лем'),
    title: 'Солярис',
    author: 'Станислав Лем',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Всего один поцелуй', 'стелла так'),
    title: 'Всего один поцелуй',
    author: 'стелла так',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Гнев богов', 'стелла так'),
    title: 'Гнев богов',
    author: 'стелла так',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Ещё один поцелуй', 'стелла так'),
    title: 'Ещё один поцелуй',
    author: 'стелла так',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Кровь богов', 'стелла так'),
    title: 'Кровь богов',
    author: 'стелла так',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Ночь Королей. Игра с судьбой', 'стелла так'),
    title: 'Ночь Королей. Игра с судьбой',
    author: 'стелла так',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Ночь Королей. Сражайся за свое сердце', 'стелла так'),
    title: 'Ночь Королей. Сражайся за свое сердце',
    author: 'стелла так',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Поцелуй меня сейчас', 'стелла так'),
    title: 'Поцелуй меня сейчас',
    author: 'стелла так',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Ритм наших сердец', 'стелла так'),
    title: 'Ритм наших сердец',
    author: 'стелла так',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Семь смертей Эвелины Хардкасл', 'Стюарт Тёртон'),
    title: 'Семь смертей Эвелины Хардкасл',
    author: 'Стюарт Тёртон',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Возроди меня', 'тахира мафи'),
    title: 'Возроди меня',
    author: 'тахира мафи',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Разрушь меня',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Вообрази меня', 'тахира мафи'),
    title: 'Вообрази меня',
    author: 'тахира мафи',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Разрушь меня',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Зажги меня', 'тахира мафи'),
    title: 'Зажги меня',
    author: 'тахира мафи',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Разрушь меня',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Одолей меня', 'тахира мафи'),
    title: 'Одолей меня',
    author: 'тахира мафи',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Разрушь меня',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Разгадай меня', 'тахира мафи'),
    title: 'Разгадай меня',
    author: 'тахира мафи',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Разрушь меня',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Разрушь меня', 'тахира мафи'),
    title: 'Разрушь меня',
    author: 'тахира мафи',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Разрушь меня',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Глубина резкости', 'Тери Нова'),
    title: 'Глубина резкости',
    author: 'Тери Нова',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Когда мы упали', 'тилли коул'),
    title: 'Когда мы упали',
    author: 'тилли коул',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Мечта для нас', 'тилли коул'),
    title: 'Мечта для нас',
    author: 'тилли коул',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Милый дом', 'тилли коул'),
    title: 'Милый дом',
    author: 'тилли коул',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Обретая надежду', 'тилли коул'),
    title: 'Обретая надежду',
    author: 'тилли коул',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Тысяча поцелуев, которые не возможно забыть', 'тилли коул'),
    title: 'Тысяча поцелуев, которые не возможно забыть',
    author: 'тилли коул',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Жажда', 'Трейси вульф'),
    title: 'Жажда',
    author: 'Трейси вульф',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Жажда',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Желание', 'Трейси вульф'),
    title: 'Желание',
    author: 'Трейси вульф',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Жажда',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Искушение', 'Трейси вульф'),
    title: 'Искушение',
    author: 'Трейси вульф',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Жажда',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Испытание', 'Трейси вульф'),
    title: 'Испытание',
    author: 'Трейси вульф',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Жажда',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Тени между нами', 'Триша Левенселлер'),
    title: 'Тени между нами',
    author: 'Триша Левенселлер',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Если однажды жизнь отнимет тебя у меня', 'Тьерри коэн'),
    title: 'Если однажды жизнь отнимет тебя у меня',
    author: 'Тьерри коэн',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('три метра над уровнем неба', 'Федерико Моччиа'),
    title: 'три метра над уровнем неба',
    author: 'Федерико Моччиа',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Преступление и наказание', 'Фёдор Достоевский'),
    title: 'Преступление и наказание',
    author: 'Фёдор Достоевский',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Великий Гэтсби', 'Фрэнсис Скотт Фицджеральд'),
    title: 'Великий Гэтсби',
    author: 'Фрэнсис Скотт Фицджеральд',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Ежевичное вино', 'Харрис Джоанн'),
    title: 'Ежевичное вино',
    author: 'Харрис Джоанн',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Земляничный вор', 'Харрис Джоанн'),
    title: 'Земляничный вор',
    author: 'Харрис Джоанн',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Пять четвертинок апельсина', 'Харрис Джоанн'),
    title: 'Пять четвертинок апельсина',
    author: 'Харрис Джоанн',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Темный ангел', 'Харрис Джоанн'),
    title: 'Темный ангел',
    author: 'Харрис Джоанн',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Чай с птицами', 'Харрис Джоанн'),
    title: 'Чай с птицами',
    author: 'Харрис Джоанн',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Шоколад', 'Харрис Джоанн'),
    title: 'Шоколад',
    author: 'Харрис Джоанн',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Жестокий принц', 'Холли Блэк'),
    title: 'Жестокий принц',
    author: 'Холли Блэк',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Воздушный народ',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Злой король', 'Холли Блэк'),
    title: 'Злой король',
    author: 'Холли Блэк',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Воздушный народ',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Королева ничего', 'Холли Блэк'),
    title: 'Королева ничего',
    author: 'Холли Блэк',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Воздушный народ',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Боги и чудовища', 'шелби махёрин'),
    title: 'Боги и чудовища',
    author: 'шелби махёрин',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Змей и голубка',
    category: BookCategory.WANT_TO_READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Змей и голубка', 'шелби махёрин'),
    title: 'Змей и голубка',
    author: 'шелби махёрин',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Змей и голубка',
    category: BookCategory.READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Кровь и мёд', 'шелби махёрин'),
    title: 'Кровь и мёд',
    author: 'шелби махёрин',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Змей и голубка',
    category: BookCategory.READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Когда ты рядом', 'Эйприл доусон'),
    title: 'Когда ты рядом',
    author: 'Эйприл доусон',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Не смыкая глаз', 'Эйприл доусон'),
    title: 'Не смыкая глаз',
    author: 'Эйприл доусон',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Никто, кроме тебя', 'Эйприл доусон'),
    title: 'Никто, кроме тебя',
    author: 'Эйприл доусон',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Босиком по асфальту', 'Элеонора Фео'),
    title: 'Босиком по асфальту',
    author: 'Элеонора Фео',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Мой лучший враг', 'Эли Фрей'),
    title: 'Мой лучший враг',
    author: 'Эли Фрей',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Дорогая Лав, я тебя ненавижу', 'Элия Гринвуд'),
    title: 'Дорогая Лав, я тебя ненавижу',
    author: 'Элия Гринвуд',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Наследие', 'Эль Кеннеди'),
    title: 'Наследие',
    author: 'Эль Кеннеди',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Ошибка', 'Эль Кеннеди'),
    title: 'Ошибка',
    author: 'Эль Кеннеди',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Риск', 'Эль Кеннеди'),
    title: 'Риск',
    author: 'Эль Кеннеди',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Сделка', 'Эль Кеннеди'),
    title: 'Сделка',
    author: 'Эль Кеннеди',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Счет', 'Эль Кеннеди'),
    title: 'Счет',
    author: 'Эль Кеннеди',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Цель', 'Эль Кеннеди'),
    title: 'Цель',
    author: 'Эль Кеннеди',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Квантовая теория недопоцелуев', 'Эми Паркс'),
    title: 'Квантовая теория недопоцелуев',
    author: 'Эми Паркс',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Мажор', 'Эмилия грин'),
    title: 'Мажор',
    author: 'Эмилия грин',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('нахал', 'Эмилия грин'),
    title: 'нахал',
    author: 'Эмилия грин',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('The muse', 'Эмма Скотт'),
    title: 'The muse',
    author: 'Эмма Скотт',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Выше только любовь', 'Эмма Скотт'),
    title: 'Выше только любовь',
    author: 'Эмма Скотт',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Грешник', 'Эмма Скотт'),
    title: 'Грешник',
    author: 'Эмма Скотт',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Дотянуться до звезд', 'Эмма Скотт'),
    title: 'Дотянуться до звезд',
    author: 'Эмма Скотт',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Зажечь небеса', 'Эмма Скотт'),
    title: 'Зажечь небеса',
    author: 'Эмма Скотт',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Как спасти жизнь', 'Эмма Скотт'),
    title: 'Как спасти жизнь',
    author: 'Эмма Скотт',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Между привет и прощай', 'Эмма Скотт'),
    title: 'Между привет и прощай',
    author: 'Эмма Скотт',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Однажды я выберу тебя', 'Эмма Скотт'),
    title: 'Однажды я выберу тебя',
    author: 'Эмма Скотт',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Пять минут жизни', 'Эмма Скотт'),
    title: 'Пять минут жизни',
    author: 'Эмма Скотт',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Сахар и золото', 'Эмма Скотт'),
    title: 'Сахар и золото',
    author: 'Эмма Скотт',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Свет между нами', 'Эмма Скотт'),
    title: 'Свет между нами',
    author: 'Эмма Скотт',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Сейчас и навечно', 'Эмма Скотт'),
    title: 'Сейчас и навечно',
    author: 'Эмма Скотт',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Среди тысячи слов', 'Эмма Скотт'),
    title: 'Среди тысячи слов',
    author: 'Эмма Скотт',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
    physicalStatus: PhysicalStatus.OWNED,
  },
  {
    id: generateId('Стань моим завтра', 'Эмма Скотт'),
    title: 'Стань моим завтра',
    author: 'Эмма Скотт',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('111', 'Эмма чейз'),
    title: '111',
    author: 'Эмма чейз',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Royal Love. Принц Генри', 'Эмма чейз'),
    title: 'Royal Love. Принц Генри',
    author: 'Эмма чейз',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Royal Love',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Royal Love. Принц Николас', 'Эмма чейз'),
    title: 'Royal Love. Принц Николас',
    author: 'Эмма чейз',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Royal Love',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Бумажная принцесса', 'Эрин Уатт'),
    title: 'Бумажная принцесса',
    author: 'Эрин Уатт',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Семья Ройалов',
    category: BookCategory.READ,
  },
  {
    id: generateId('Запятнная корона', 'Эрин Уатт'),
    title: 'Запятнная корона',
    author: 'Эрин Уатт',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Семья Ройалов',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Отвергнутый наследник', 'Эрин Уатт'),
    title: 'Отвергнутый наследник',
    author: 'Эрин Уатт',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Семья Ройалов',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Разрушенный дворец', 'Эрин Уатт'),
    title: 'Разрушенный дворец',
    author: 'Эрин Уатт',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Семья Ройалов',
    category: BookCategory.READ,
  },
  {
    id: generateId('Расколотое королевство', 'Эрин Уатт'),
    title: 'Расколотое королевство',
    author: 'Эрин Уатт',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Семья Ройалов',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Сломленный принц', 'Эрин Уатт'),
    title: 'Сломленный принц',
    author: 'Эрин Уатт',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: 'Семья Ройалов',
    category: BookCategory.READ,
  },
  {
    id: generateId('Злая принцесса', 'Эшли Джейд'),
    title: 'Злая принцесса',
    author: 'Эшли Джейд',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('Кругом одни невесты', 'Юлия Набокова'),
    title: 'Кругом одни невесты',
    author: 'Юлия Набокова',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
  {
    id: generateId('невеста на уикенд', 'юлия цыпленкова'),
    title: 'невеста на уикенд',
    author: 'юлия цыпленкова',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.READ,
  },
  {
    id: generateId('Тоннель', 'Яна Вагнер'),
    title: 'Тоннель',
    author: 'Яна Вагнер',
    description: 'Описание будет добавлено позже.',
    publisher: 'Не указан',
    series: '',
    category: BookCategory.WANT_TO_READ,
  },
];
